# Generated by Django 5.2.3 on 2025-06-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_courselist_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.courselist')),
            ],
        ),
        migrations.CreateModel(
            name='SponsershipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Percentage completed(0-100)')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.studentrecord')),
            ],
        ),
    ]
