# Generated by Django 5.2.3 on 2025-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_studentrecord_sponsershipdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='complete_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
