# Generated by Django 5.2.3 on 2025-06-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_studentrecord_complete_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsershipdetail',
            name='progress',
        ),
    ]
