# Generated by Django 5.2.3 on 2025-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_remove_sponsershipdetail_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='progress',
            field=models.IntegerField(default=0, help_text='Percentage completed(0-100)'),
        ),
    ]
