# Generated by Django 5.2.3 on 2025-06-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_assessment_studentrecord_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.assessment'),
        ),
    ]
