# Generated by Django 5.2.3 on 2025-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_courselist_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course_deadlines',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
